silo-finance/silo-contracts-v2

- silo-core/contracts/SiloFactory.sol
- silo-core/contracts/interfaces/ISiloFactory.sol
- silo-core/test/foundry/SiloFactory/SiloFactoryCreateSiloTest.t.sol
- silo-core/test/foundry/SiloFactory/SiloFactorySettersTest.t.sol
- silo-core/test/foundry/SiloFactory/SiloFactoryTest.t.sol
- silo-core/test/foundry/_common/SiloLittleHelper.sol
- silo-core/test/foundry/_protocol/ERC4626Compliance.t.sol
- silo-core/test/foundry/lib/SiloStdLib/GetFeesAndFeeReceiversWithAsset.t.sol
- new error `DaoFeeReceiverZeroAddress`
- added `ERC4626ComplianceTest`
> better error name and `ERC4626ComplianceTest`

- CHANGELOG.md
- silo-vaults/common/SiloVaultsContracts.sol
- silo-vaults/contracts/PublicAllocator.sol
- silo-vaults/contracts/interfaces/IPublicAllocator.sol
- silo-vaults/contracts/libraries/ErrorsLib.sol
- silo-vaults/contracts/libraries/EventsLib.sol
- silo-vaults/deploy/PublicAllocatorDeploy.s.sol
- silo-vaults/test/foundry/PublicAllocatorTest.sol
original code: https://github.com/morpho-org/public-allocator/tree/v1.0.0
forking PR: https://github.com/silo-finance/silo-contracts-v2/pull/843
> silo-vaults: public allocator for vault standard

- CHANGELOG.md
- silo-core/contracts/lib/Actions.sol
- silo-core/test/foundry/Silo/reentrancy/MaliciousToken.sol
- silo-core/test/foundry/Silo/reentrancy/SiloReentrancy.t.sol
- silo-core/test/foundry/Silo/reentrancy/methods/silo/WithdrawFeesReentrancyTest.sol
- silo-core/test/foundry/_mocks/SiloConfigMock.sol
- silo-core/test/foundry/lib/SiloStdLib/WithdrawFees.t.sol
> [L-01] silo-core: add reentrancy for withdrawFees

- silo-core/contracts/Silo.sol
- silo-core/contracts/interfaces/IERC3156FlashBorrower.sol
- silo-core/contracts/interfaces/IERC3156FlashLender.sol
> silo-core: flashloan comment

- silo-core/contracts/Silo.sol
- silo-core/contracts/SiloConfig.sol
- silo-core/contracts/SiloLens.sol
- silo-core/contracts/incentives/SiloIncentivesController.sol
- silo-core/contracts/incentives/base/BaseIncentivesController.sol
- silo-core/contracts/incentives/base/DistributionManager.sol
- silo-core/contracts/interestRateModel/InterestRateModelV2.sol
- silo-core/contracts/utils/ShareToken.sol
- silo-core/contracts/utils/liquidationHelper/DexSwap.sol
- silo-core/contracts/utils/liquidationHelper/LiquidationHelper.sol
- silo-oracles/contracts/custom/WusdPlusUsdAdapter.sol
- silo-vaults/contracts/IdleVault.sol
- silo-vaults/contracts/PublicAllocator.sol
- silo-vaults/contracts/SiloVault.sol
- silo-vaults/contracts/SiloVaultsFactory.sol
- silo-vaults/contracts/incentives/VaultIncentivesModule.sol
- silo-vaults/contracts/incentives/claiming-logics/SiloIncentivesControllerCL.sol
> add `virtual`

- silo-vaults/common/SiloVaultsContracts.sol
- silo-vaults/contracts/IdleVaultsFactory.sol
- silo-vaults/contracts/libraries/EventsLib.sol
- silo-vaults/deploy/IdleVaultsFactoryDeploy.s.sol
- silo-vaults/test/foundry/helpers/BaseTest.sol
> silo-vaults: idle vault factory

- silo-core/contracts/utils/hook-receivers/_common/BaseHookReceiver.sol
- silo-core/contracts/utils/hook-receivers/gauge/GaugeHookReceiver.sol
- silo-core/test/foundry/_mocks/SiloHookReceiverHarness.sol
- silo-core/test/foundry/utils/hook-receivers/SiloHookReceiver.t.sol
12. Potentially Inaccurate hooksBefore - DONE
13. Data Type Mismatch Related Asset(s): SiloHookReceiver.sol - DONE
> silo-core: cleanup hooks types

- silo-vaults/contracts/SiloVault.sol
- silo-vaults/test/foundry/FeeTest.sol
fixes: L-05 Fee Recipient could lose rewards for newly generated fees
> silo-core: accrue fees on claiming rewards

- CHANGELOG.md
- silo-core/contracts/incentives/base/DistributionManager.sol
- silo-core/test/foundry/debug/Incentives2025_01_18.sol
- silo-core/test/foundry/incentives/SiloIncentivesController.t.sol
- silo-vaults/contracts/SiloVault.sol
- silo-vaults/contracts/libraries/ConstantsLib.sol
- silo-vaults/contracts/libraries/ErrorsLib.sol
- silo-vaults/contracts/libraries/SiloVaultActionsLib.sol
- silo-vaults/test/foundry/ERC4626Test.sol
- silo-vaults/test/foundry/FeeTest.sol
- silo-vaults/test/foundry/SiloVaultInternalTest.sol
- silo-vaults/test/foundry/fromCore/max/maxDeposit/MaxMint.i.sol
- silo-vaults/test/foundry/fromCore/max/maxWithdraw/MaxRedeem.i.sol
- silo-vaults/test/foundry/fromCore/max/maxWithdraw/MaxWithdraw.i.sol
- silo-vaults/test/foundry/fromCore/preview/previewWithdraw/PreviewRedeem.i.sol
- silo-vaults/test/foundry/fromCore/preview/previewWithdraw/PreviewWithdraw.i.sol
- silo-vaults/test/foundry/helpers/BaseTest.sol
- silo-vaults/test/foundry/incentives/VaultMultipleRewards.i.sol
- silo-vaults/test/foundry/incentives/VaultRewardsIntegration.i.sol
- silo-vaults/test/foundry/incentives/VaultsSiloIncentives.i.sol
> L-06 Vault could be vulnerable to an inflation attack

- silo-vaults/contracts/SiloVault.sol
- silo-vaults/contracts/libraries/SiloVaultActionsLib.sol
`SiloVaultsFactory  free space: 31 -> 768`
> reduce vault size

- silo-vaults/contracts/SiloVault.sol
base on this comment https://github.com/silo-finance/silo-contracts-v2/pull/1162#pullrequestreview-2759382306
> silo-vault: optimise check for zero shares

- silo-core/contracts/Silo.sol
we can also do `-1` on totalAssets.
> comment about fractions

- .github/workflows/silo-vaults.yml
- silo-vaults/test/foundry/ERC4626Test.sol
- silo-vaults/test/foundry/call-and-reenter/methods/WithdrawReentrancyTest.sol
- silo-vaults/test/foundry/fromCore/preview/previewWithdraw/PreviewWithdraw.i.sol
- silo-vaults/test/foundry/lossCheck/MarketLoss.t.sol
> silo-vaults: test adjustments due to silo underestimation in max fn

- x-silo/contracts/modules/XRedeemPolicy.sol
- x-silo/test/foundry/XSilo.t.sol
- x-silo/test/foundry/modules/XRedeemPolicy.t.sol
M-04 Low vesting precision yields discrete steps and up to 1.5% loss of funds for users
Fixes: Silo-3968
> [M-04] x-silo: user higher precision

- .github/PULL_REQUEST_TEMPLATE.md
It should be good practice to give some description to any PR we doing, even small one. It will help reviewer to understand problem quicker and better.
Basic description should be required to any PR.
we can think about predefined (optional) sections to add to this template now, or we can add add-hock.
Create general PR template that will help us to describe PR.
> make PR description required

- x-silo/deployments/sonic/Stream.sol.json
- x-silo/deployments/sonic/XSilo.sol.json
production deployment for:
- [XSilo](https://sonicscan.org/address/0x4451765739b2d7bce5f8bc95beaf966c45e1dcc9)
- [Stream](https://sonicscan.org/address/0x023d9bcb63532d1215d4adbdb66a4410e506b90e)
please check if:
> x-silo: production deployment

- silo-core/deployments/sonic/LeverageUsingSiloFlashloanWithGeneralSwap.sol.json
> silo-core: leverage alpha deployment

- silo-core/deploy/input/_importFromCsv/marketImport.py
Script for importing config data fails
Turns out we have to adjust keys, last one turns out not to be used now.
> silo-core: fix keys for importing script

- silo-oracles/deploy/chainlink-v3-oracle/ChainlinkV3OracleDeploy.s.sol
verification of such an numbers is painful and open for human errors
```
Quote for 10wei is 4
Quote for 1000000wei is 400239
Quote for 100000000wei is 40023972
Quote for 1000000000000000000wei is 400239720000000000
Quote for 1000000000000000000000000000000000000wei is 400239720000000000000000000000000000
```
print numbers in `e` format
```
Quote for 10 wei is 4
Quote for 1000000 wei is 400239
Quote for 1e8 wei is 40023972
Quote for 1e18 wei is 40023972e10
Quote for 1e36 wei is 40023972e28
```
we can improve this format later eg to force `e18`. But even with this formatting it is huge help when we do verification.
> silo-coracle: print numbers that are easy to verify by human

- silo-core/deploy/silo/verifier/Logger.sol
Fixes SILO-
For Pendle LPT markets silo verifier missed underlying oracle info
Refactored SiloVerifier to show underlying oracle info for the Pendle LPT markets
> silo-core: SiloVerifier for the Pendle LPT markets

- silo-oracles/deploy/pendle/PendleWrapperLPTToSyOracleDeploy.s.sol
Deployment script for the `PendleWrapperLPTToSyOracle`
> silo-core: Pendle wrapper LPT toSy oracle deploy

- silo-core/deploy/TowerRegistration.s.sol
- silo-core/deployments/mainnet/LeverageUsingSiloFlashloanWithGeneralSwap.sol.json
- silo-core/deployments/sonic/LeverageUsingSiloFlashloanWithGeneralSwap.sol.json
- silo-vaults/test/foundry/ERC4626Test.sol
After audit we fix one issue, redeployment is needed.
- Leverage live deployment. 
- Updated Tower script to register leverage
> silo-core: leverage live deployment for sonic, mainnet

- .github/workflows/verify-silo.yml
we can make human errors when running script and paste results to PR desc.
run script automatically and create comment with results. See how it works here: https://github.com/silo-finance/silo-contracts-v2/pull/1424#issuecomment-2990327664
all you need to do is set prices anywhere in PR description like:
EXTERNAL_PRICE_0=123
EXTERNAL_PRICE_1=456
> silo-core: run verification script in CI

- silo-core/contracts/SiloLens.sol
- silo-core/contracts/interfaces/ISiloLens.sol
- silo-core/test/foundry/SiloLens/SiloLens.t.sol
- silo-core/test/foundry/SiloLens/SiloLensCompatibility.i.sol
- silo-vaults/test/foundry/lossCheck/MarketLoss.t.sol
Fixes SILO-3700
https://silofinance.atlassian.net/browse/SILO-3700
add dedicated view method
> silo-core: getOracleAddresses

- silo-core/scripts/towerRegistration.sh
When we re-deploy some contracts we need to register in Tower. This can be automated.
Bash script to call to register on all blockchains
> tower registration for all blockchains

- silo-core/test/echidna-leverage/CryticToFoundryLeverage.t.sol
- silo-core/test/invariants/hooks/DefaultBeforeAfterHooks.t.sol
Fixes SILO-4200
add share balances to default vars
> echidna-leverage: store actor share balances

- silo-core/test/echidna-leverage/handlers/user/LeverageHandler.t.sol
Fixes SILO-4200
invalid signature was used for leverage calls
use proper signature
> echidna-leverage: fix leverage call

- silo-core/test/foundry/Silo/max/maxBorrow/MaxBorrowAndFractions.i.sol
Fuzzing test failing
Require maxBorrow to be non zero
> silo-core: MaxBorrowAndFractions test todos

- silo-core/docs/DeployedSiloVersions.md
- silo-core/scripts/avalanche_silo_analyzer.py
Fixes SILO-4543
Missing info about avalanche deployements
add info
> deployed silo lending markets versions on Avalanche
